title: Dhiego Silva
description: all double programming

url: https://github.com/Dh13G0Silva
baseurl: ""
paginate_path: "/page:num/"
permalink: /:title.html

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: Dh13G0Silva
   twitter: Dh13G0_Silva
   facebook: Blacksystembr
   email: francisco.dhiego17@gmail.com

google_analytics: "UA-111417866-1"
